### ISSUE TITLE
redefine error when include “cpp-semver.hpp“ in multiple CPP files

### ISSUE THREAD

**Issue by returnzero23** [easz/cpp-semver#3]
Do you notice that? This causes me to use the extern declaration where I also want to use semver-cpp.

**Comment by easz** [comment]
I will take a look at it

**Comment by easz** [comment]
hi, how did you use the header file? can you give an example?
what exactly does it include in multiple cpp files?
the `test/` folder has also multiple cpp files which all include  `cpp-semver.hpp`

**Comment by returnzero23** [comment]
no error , each of cpp files in the test/ folder  is a separate program.
there are errors where cpp-semver.hpp was included in multiple cpp files that are in a single program.
such as 

##file:a.cpp

#include "cpp-semver.hpp"

##file:b.cpp

#include "cpp-semver.hpp"

##file: main.cpp

#include a.h
#include b.h

This violates the One Definition Rule (ODR), so that I  need a extern extern declaration where I want to use semver in mutiple cpp files.

Could you implement semver in cpp files.

or if you want to implement it in headers, you can use static function and class like (nlohmann-json)[https://github.com/nlohmann/json/blob/develop/include/nlohmann/json.hpp]

**Comment by easz** [comment]
or `inline` functions? would it help?
https://stackoverflow.com/questions/3973218/header-only-libraries-and-multiple-definition-errors

**Comment by returnzero23** [comment]
yes,it works. but i don`t want to modify the headers in library, because I want to keep the library is clean.  I prefer to use extern declaration.
thanks for you reply.
: )

**Comment by GPBeta** [comment]
Same issues here. Please consider adding `inline` declaration or replacing some nested name spaces with classes.
I believe this is the best `npm semver` cpp  implementation on Github, just keep this great work!

**Comment by easz** [comment]
sorry for the delay :(   any **PR** is welcome to improve it, otherwise it may take week(s) for me to back to the work....

**Comment by GPBeta** [comment]
Done.
I also notice that I got ~50% poorer performance and ~10% larger size with the `PEGTL parser` in release build, so what is the general purpose of this option for?

**Comment by easz** [comment]
Pegtl parser is actually used at the beginning to quick parse input.  And
to cross test own implementation.
